### ISSUE TITLE
gulp watch throws error on wrong scss syntax

### ISSUE THREAD

**Issue by donlion** [Cabana/boilerplate-nodejs#1]
![screen shot 2015-06-22 at 10 32 52](https://cloud.githubusercontent.com/assets/2965242/8278263/409a68b6-18ca-11e5-9cb0-b48799c5ba0c.png)
![screen shot 2015-06-22 at 10 32 43](https://cloud.githubusercontent.com/assets/2965242/8278264/409da24c-18ca-11e5-9df9-007ceafd4892.png)

**Comment by motiejuss** [comment]
https://github.com/google/web-starter-kit/pull/708 and updated to 2.0.2, although it doesn't fix this. You can set `errLogToConsole` to `false` and it won't stop watching or wait for the next version. :)
